In [1]:
import adaboost

In [2]:
dataMat, classLabels = adaboost.loadSimpData()

In [3]:
dataMat

matrix([[1. , 2.1],
        [2. , 1.1],
        [1.3, 1. ],
        [1. , 1. ],
        [2. , 1. ]])

In [4]:
classLabels

[1.0, 1.0, -1.0, -1.0, 1.0]

In [5]:
import numpy as np

In [6]:
  D = np.mat(np.ones((5, 1)) / 5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

In [7]:
D

matrix([[0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.2]])

In [8]:
adaboost.buildStump(dataMat, classLabels, D)

({'dim': 0, 'ineq': 'lt', 'thresh': 1.3}, matrix([[0.2]]), array([[-1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]]))

In [10]:
weakClassArr = adaboost.adaBoostTrainDS(dataMat, classLabels)

total error:  0.2
total error:  0.2
total error:  0.0


In [11]:
weakClassArr

[{'alpha': 0.6931471805599453, 'dim': 0, 'ineq': 'lt', 'thresh': 1.3},
 {'alpha': 0.9729550745276565, 'dim': 1, 'ineq': 'lt', 'thresh': 1.0},
 {'alpha': 0.8958797346140273, 'dim': 0, 'ineq': 'lt', 'thresh': 0.9}]

In [12]:
adaboost.adaClassify([0, 0], weakClassArr)

[[-0.69314718]]
[[-1.66610226]]
[[-2.56198199]]


matrix([[-1.]])